function generateAndStoreApiKeyInSheet(payload) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);

  try {
    const input = payload || {};
    const generatedBy = asString_(input.generated_by || Session.getActiveUser().getEmail() || 'manual-editor').trim();
    const note = asString_(input.note || 'Generated by Apps Script helper').trim();
    const spreadsheet = resolveSpreadsheetForSecrets_(input);
    ensureRequiredTabs_(spreadsheet);
    const sheet = getSheetByNameOrCreate_(spreadsheet, APP_CONFIG.SECRETS_TAB_NAME);
    const headers = getSecretsHeaders_();
    ensureSheetHeadersExact_(sheet, headers);

    const newApiKey = generateAppScriptApiKey_();
    getScriptProperties_().setProperty(APP_CONFIG.API_KEY_PROPERTY, newApiKey);
    upsertIntegrationSecretRow_(sheet, headers, 'APPS_SCRIPT_API_KEY', newApiKey, generatedBy, note);

    return {
      ok: true,
      action: 'generate_api_key',
      sheet_name: APP_CONFIG.SECRETS_TAB_NAME,
      spreadsheet_id: spreadsheet.getId(),
      spreadsheet_url: spreadsheet.getUrl(),
      generated_at: nowIso_(),
      masked_key: maskSecret_(newApiKey),
      message: 'A new API key was generated, stored in Script Properties, and written to the Integration Secrets sheet.'
    };
  } finally {
    lock.releaseLock();
  }
}

function rotateApiKeyFromEditor() {
  return generateAndStoreApiKeyInSheet({
    generated_by: Session.getActiveUser().getEmail() || 'manual-editor',
    note: 'Manual rotation from Apps Script editor',
    use_active_spreadsheet: true
  });
}

function debugSecretsStorageLocation() {
  const spreadsheet = resolveSpreadsheetForSecrets_({ use_active_spreadsheet: true });
  const sheet = getSheetByNameOrCreate_(spreadsheet, APP_CONFIG.SECRETS_TAB_NAME);
  const headers = getSecretsHeaders_();
  ensureSheetHeadersExact_(sheet, headers);
  return {
    ok: true,
    spreadsheet_id: spreadsheet.getId(),
    spreadsheet_url: spreadsheet.getUrl(),
    sheet_name: sheet.getName(),
    sheet_id: sheet.getSheetId(),
    last_row: sheet.getLastRow()
  };
}

function bindManagedSpreadsheetIdFromEditor(spreadsheetId) {
  const trimmed = asString_(spreadsheetId).trim();
  if (!trimmed) {
    throw new Error('spreadsheetId is required.');
  }
  const spreadsheet = SpreadsheetApp.openById(trimmed);
  getScriptProperties_().setProperty(APP_CONFIG.SHEET_ID_PROPERTY, spreadsheet.getId());
  return {
    ok: true,
    spreadsheet_id: spreadsheet.getId(),
    spreadsheet_url: spreadsheet.getUrl(),
    message: 'GOOGLE_SHEET_ID was updated in Script Properties.'
  };
}

function bindManagedSpreadsheetToActiveFromEditor() {
  const active = SpreadsheetApp.getActiveSpreadsheet();
  if (!active) {
    throw new Error('No active spreadsheet detected. Open the target spreadsheet and run this function again.');
  }
  getScriptProperties_().setProperty(APP_CONFIG.SHEET_ID_PROPERTY, active.getId());
  return {
    ok: true,
    spreadsheet_id: active.getId(),
    spreadsheet_url: active.getUrl(),
    message: 'GOOGLE_SHEET_ID was set to the active spreadsheet.'
  };
}

function generateAppScriptApiKey_() {
  const part1 = Utilities.getUuid().replace(/-/g, '');
  const part2 = Utilities.getUuid().replace(/-/g, '');
  const part3 = Utilities.base64EncodeWebSafe(
    Utilities.computeDigest(
      Utilities.DigestAlgorithm.SHA_256,
      part1 + part2 + nowIso_(),
      Utilities.Charset.UTF_8
    )
  ).replace(/=/g, '');
  return 'as_' + part3.substring(0, 56);
}

function upsertIntegrationSecretRow_(sheet, headers, keyName, keyValue, generatedBy, note) {
  ensureSheetHeadersExact_(sheet, headers);

  const currentValues = sheet.getDataRange().getValues();
  const headerRow = currentValues[0].map(function eachHeader(value) {
    return asString_(value).trim();
  });
  const idx = indexByHeaders_(headerRow);
  const timestamp = nowIso_();

  for (let row = 1; row < currentValues.length; row += 1) {
    const rowKeyName = asString_(currentValues[row][idx.key_name]).trim();
    if (rowKeyName !== keyName) {
      continue;
    }
    currentValues[row][idx.key_value] = keyValue;
    currentValues[row][idx.generated_at] = timestamp;
    currentValues[row][idx.generated_by] = generatedBy;
    currentValues[row][idx.note] = note;
    currentValues[row][idx.is_active] = 'true';
    sheet.getRange(1, 1, currentValues.length, currentValues[0].length).setValues(currentValues);
    return;
  }

  appendRowsByHeader_(sheet, headers, [
    {
      key_name: keyName,
      key_value: keyValue,
      generated_at: timestamp,
      generated_by: generatedBy,
      note: note,
      is_active: 'true'
    }
  ]);
}

function maskSecret_(value) {
  const raw = asString_(value);
  if (raw.length < 8) {
    return '***';
  }
  return raw.substring(0, 4) + '***' + raw.substring(raw.length - 4);
}

function getSecretsHeaders_() {
  const tabDef = getTabDefinitionByName_(APP_CONFIG.SECRETS_TAB_NAME);
  if (tabDef && Array.isArray(tabDef.headers) && tabDef.headers.length > 0) {
    return tabDef.headers;
  }
  return ['key_name', 'key_value', 'generated_at', 'generated_by', 'note', 'is_active'];
}

function ensureSheetHeadersExact_(sheet, headers) {
  const maxCols = Math.max(sheet.getLastColumn(), headers.length);
  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    return;
  }

  const existing = sheet.getRange(1, 1, 1, maxCols).getValues()[0].map(function eachValue(value) {
    return asString_(value).trim();
  });

  let matches = true;
  for (let i = 0; i < headers.length; i += 1) {
    if (asString_(existing[i]).trim() !== asString_(headers[i]).trim()) {
      matches = false;
      break;
    }
  }

  if (!matches) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  }
}

function resolveSpreadsheetForSecrets_(input) {
  const props = getScriptProperties_();
  const payload = input || {};

  if (payload.spreadsheet_id) {
    const byId = SpreadsheetApp.openById(asString_(payload.spreadsheet_id).trim());
    props.setProperty(APP_CONFIG.SHEET_ID_PROPERTY, byId.getId());
    return byId;
  }

  if (payload.use_active_spreadsheet) {
    const active = SpreadsheetApp.getActiveSpreadsheet();
    if (active) {
      props.setProperty(APP_CONFIG.SHEET_ID_PROPERTY, active.getId());
      return active;
    }
  }

  const propertySheetId = asString_(props.getProperty(APP_CONFIG.SHEET_ID_PROPERTY)).trim();
  if (propertySheetId) {
    try {
      return SpreadsheetApp.openById(propertySheetId);
    } catch (error) {
      props.deleteProperty(APP_CONFIG.SHEET_ID_PROPERTY);
    }
  }

  return openManagedSpreadsheet_();
}
